# Generated by Django 4.2.11 on 2025-12-11 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
from datetime import date


ALLOWED_SUBJECTS = {
    "BANGLA": "BAN-101",
    "ENGLISH": "ENG-101",
    "MATH": "MAT-101",
    "SCIENCE": "SCE-101",
    "ISLAMIC STUDIES": "ISL-101",
}


def cleanup_and_seed(apps, schema_editor):
    Subject = apps.get_model("academics", "Subject")
    AcademicYear = apps.get_model("academics", "AcademicYear")
    Enrollment = apps.get_model("academics", "Enrollment")
    Assignment = apps.get_model("academics", "Assignment")
    from django.utils import timezone

    AcademicYear.objects.exclude(year__in=[str(y) for y in range(2024, 2051)]).update(is_current=False)
    # Drop duplicate enrollments per student/year to satisfy new uniqueness.
    seen_enrollments = set()
    for enrollment in Enrollment.objects.order_by("id"):
        key = (enrollment.student_id, enrollment.academic_year_id)
        if key in seen_enrollments:
            enrollment.delete()
        else:
            seen_enrollments.add(key)

    # Drop duplicate assignments per class/subject/year so one teacher owns a subject.
    seen_assignments = set()
    for assignment in Assignment.objects.order_by("id"):
        key = (assignment.academic_year_id, assignment.class_offering_id, assignment.subject_id)
        if key in seen_assignments:
            assignment.delete()
        else:
            seen_assignments.add(key)

    # Enforce hardcoded subjects.
    allowed_names = [name.title() for name in ALLOWED_SUBJECTS.keys()]
    Subject.objects.exclude(name__in=allowed_names).delete()
    for name_upper, code in ALLOWED_SUBJECTS.items():
        Subject.objects.update_or_create(code=code, defaults={"name": name_upper.title()})

    # Seed academic years 2024-2050 and mark only the running year as current.
    current_year = timezone.localdate().year
    for yr in range(2024, 2051):
        start = date(yr, 1, 1)
        end = date(yr, 12, 31)
        year_obj, _ = AcademicYear.objects.get_or_create(
            year=str(yr),
            defaults={"start_date": start, "end_date": end, "is_current": yr == current_year},
        )
        year_obj.start_date = start
        year_obj.end_date = end
        year_obj.is_current = yr == current_year
        year_obj.save(update_fields=["start_date", "end_date", "is_current"])


class Migration(migrations.Migration):

    atomic = False

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_enrollment_roll_and_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('promoted_count', models.PositiveIntegerField(default=0)),
                ('retained_count', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='enrollment',
            name='unique_roll_per_class_year',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.RunPython(cleanup_and_seed, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('academic_year', 'class_offering', 'subject'), name='unique_assignment_per_class_subject_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(condition=models.Q(('roll_number', None), _negated=True), fields=('academic_year', 'class_offering', 'roll_number'), name='unique_roll_per_class_year'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'academic_year'), name='unique_student_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_subject_name_ci'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotion_runs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='source_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_sources', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='source_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academics.classoffering'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='target_academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_targets', to='academics.academicyear'),
        ),
        migrations.AddField(
            model_name='promotionrecord',
            name='target_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='academics.classoffering'),
        ),
    ]
